### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by riimuru** [plasticuproject/clevercord#1] opened 2021-01-06 05:23 UTC
I keep getting KeyError. it says Key Error and it shows my token. Help please

**Comment by plasticuproject** [comment] 2021-01-06 11:08
You'll have to provide more information than that. Post your all your build commands and output.

**Comment by riimuru** [comment] 2021-01-06 15:08
when build image on docker from the dockerfile and i run the code on docker this on the logs and i tried running clevercode.py file and i get the same error:

Traceback (most recent call last):
File "./clevercord.py", line 33, in <module>
token = os.environ['Nzk2MTg1NjIyMzk3MTkwMjE1.X_UPpA.y8hG6PlBB0iUBsqkS5bPwrdIz-0']
File "/usr/lib/python3.6/os.py", line 669, in __getitem__
raise KeyError(key) from None
KeyError: 'Nzk2MTg1NjIyMzk3MTkwMjE1.X_UPpA.y8hG6PlBB0iUBsqkS5bPwrdI9-0'

**Comment by plasticuproject** [comment] 2021-01-06 17:17
I cloned this repo, followed my directions and everything went as expected. I don't know what you are doing wrong and you are not providing enough information for me to help you. Here are pictures of me cloning, building, and running.

![1](https://user-images.githubusercontent.com/19690649/103799234-d224db00-5018-11eb-84e0-24168b1ffaa3.png)
![2](https://user-images.githubusercontent.com/19690649/103799251-d8b35280-5018-11eb-969e-b561da13f8c8.png)
![3](https://user-images.githubusercontent.com/19690649/103799260-dbae4300-5018-11eb-8a60-2e51f1112cd2.png)

**Comment by plasticuproject** [comment] 2021-01-06 17:20
Is your token good?? The problem has to be with how you are not following directions properly, or your token is no good. Also, I hope you didn't just post your actual token above, if so you need to delete that bot token, it is no good anymore. I'll be closing this issue as I can't reproduce your problem.

**Comment by riimuru** [comment] 2021-01-06 17:23
okay i will try with ubunut i haven't tried it yet. that was fake token. you can close the issue

**Closed as completed** 2021-01-06 17:27 UTC
